### ISSUE TITLE
Export option

### ISSUE THREAD

**Issue by alivarastepour** [app-generator/devtool-python-converter#10]
tell me more about the Export option. what does it do?

**Comment by app-generator** [comment]
Hello @alivarastepour 

The DT JS Library supports by default a few formats:

https://fiduswriter.github.io/Simple-DataTables/11-export/

here is the list for the view:

- CSV: useful when the input is Pandas DF
  - (provided for all inputs, even is redundant for CSV input) 
- JSON
- SQL
- PDF 

Let me know if you need more input. ty! 

P.S. The position of the controls is not important at the moment. We can improve the layout in 2nd iteration.
Here is the default position for default buttons. 

![image](https://user-images.githubusercontent.com/51070104/205912536-bff5a07c-c093-4683-8b1f-50043853e914.png)

**Comment by app-generator** [comment]
Hello @alivarastepour 

Any progress here? Ty

**Comment by alivarastepour** [comment]
Hi, @app-generator 
we're on it. will notice you soon.

**Comment by app-generator** [comment]
🚀🚀

**Comment by alivarastepour** [comment]
exporting files to PDF is not working. any ideas?

**Comment by app-generator** [comment]
Hello Ali, 
We can skip the PDF Export for this iteration. 

The feature is already coded here, please take a look: 

https://github.com/app-generator/django-dynamic-datatb

Ty!

**Comment by app-generator** [comment]
Hello @alivarastepour 

> Please update your local copy. I did some commits. 

I see a small issue related to export. Only the first page is exported.
The desired behavior is to export all files. 

## How to reproduce 

- start app
- use [csv_titanic](https://github.com/app-generator/devtool-python-converter/tree/master/inputs) as input 
- convert to datatable (to visualize the data)
- export to JSON -> NOT_OK

The exported file has only the first page. 

Please take a look, ty!

**Comment by app-generator** [comment]
P.S. please take a look at (`enhancement`) #19 
Ty!

**Comment by alivarastepour** [comment]
> Hello @alivarastepour
> 
> > Please update your local copy. I did some commits.
> 
> I see a small issue related to export. Only the first page is exported. The desired behavior is to export all files.
> 
> ## How to reproduce
> * start app
> * use [csv_titanic](https://github.com/app-generator/devtool-python-converter/tree/master/inputs) as input
> * convert to datatable (to visualize the data)
> * export to JSON -> NOT_OK
> 
> The exported file has only the first page.
> 
> Please take a look, ty!

Hi @app-generator 
there are not enough resources about simple datatables js on the internet to solve this matter as far as I could go. any suggestions?

**Comment by app-generator** [comment]
@alivarastepour is ok.
We can leave it for now. 

ty :)

**Comment by app-generator** [comment]
Drop1 ready. validated.
Ty @alivarastepour
