### ISSUE TITLE
OpenApi YAML - Conversions / All Broken 

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#13]
Hello @Mortrest,

The OpenAPI YAML definitions are not working. The server returns ERR 500.

Here is the LOG & the **sshot**.

Please take a look. Ty! 

![image](https://user-images.githubusercontent.com/51070104/206274642-54610262-534f-4698-8df3-5e30e861f7db.png)

```log
127.0.0.1 - - [07/Dec/2022 21:09:49] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\work\repo-tools\devtool-python-converter\app\views.py", line 83, in index
    django_response = convert_openapi_yaml_to_django_models(app.config['UPLOAD_FOLDER'], filename)
  File "D:\work\repo-tools\devtool-python-converter\py_data_converter\converter_openapi.py", line 52, in convert_openapi_yaml_to_django_models
    return convert_openapi_json_to_django_models(input_address, "/converted_to_json.json")
  File "D:\work\repo-tools\devtool-python-converter\py_data_converter\converter_openapi.py", line 32, in convert_openapi_json_to_django_models
    openAPI_schema = Parse_input(input_address, filename)
  File "D:\work\repo-tools\devtool-python-converter\py_data_converter\converter_openapi.py", line 15, in Parse_input
    allthekeys = [*get_keys(source)]
  File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 41, in get_keys
    yield from get_keys(v, curr_key + [k])
  File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 41, in get_keys
    yield from get_keys(v, curr_key + [k])
  File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 41, in get_keys
    yield from get_keys(v, curr_key + [k])
  File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 44, in get_keys
    yield from get_keys(i, curr_key + [k])
    rv = self.dispatch_request()
```

**Comment by masoom80** [comment]
> Hello @Mortrest,
> 
> The OpenAPI YAML definitions are not working. The server returns ERR 500.
> 
> Here is the LOG & the **sshot**.
> 
> Please take a look. Ty!
> 
> ![image](https://user-images.githubusercontent.com/51070104/206274642-54610262-534f-4698-8df3-5e30e861f7db.png)
> 
> ```
> 127.0.0.1 - - [07/Dec/2022 21:09:49] "POST / HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 2091, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 2076, in wsgi_app
>     response = self.handle_exception(e)
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
>     response = self.full_dispatch_request()
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "D:\work\repo-tools\devtool-python-converter\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "D:\work\repo-tools\devtool-python-converter\app\views.py", line 83, in index
>     django_response = convert_openapi_yaml_to_django_models(app.config['UPLOAD_FOLDER'], filename)
>   File "D:\work\repo-tools\devtool-python-converter\py_data_converter\converter_openapi.py", line 52, in convert_openapi_yaml_to_django_models
>     return convert_openapi_json_to_django_models(input_address, "/converted_to_json.json")
>   File "D:\work\repo-tools\devtool-python-converter\py_data_converter\converter_openapi.py", line 32, in convert_openapi_json_to_django_models
>     openAPI_schema = Parse_input(input_address, filename)
>   File "D:\work\repo-tools\devtool-python-converter\py_data_converter\converter_openapi.py", line 15, in Parse_input
>     allthekeys = [*get_keys(source)]
>   File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 41, in get_keys
>     yield from get_keys(v, curr_key + [k])
>   File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 41, in get_keys
>     yield from get_keys(v, curr_key + [k])
>   File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 41, in get_keys
>     yield from get_keys(v, curr_key + [k])
>   File "D:\work\repo-tools\devtool-python-converter\py_data_converter\jsonparser.py", line 44, in get_keys
>     yield from get_keys(i, curr_key + [k])
>     rv = self.dispatch_request()
> ```

hi there!
this problem is caused by jsonparser which was written in another [project](https://github.com/app-generator/devtool-openapi-parser)  pleases send me the exact file you used.
and should I change the codes in jsonparser?

**Comment by app-generator** [comment]
Hello @masoom80 

We can leave it as it is in this iteration. Just ignore the issue. 
I will make the fix.

**Comment by app-generator** [comment]
P.S. the INPUT for all tests is saved in `inputs` DIR, and the file is `oa_product_yaml` the YAML version of `oa_product_json`.

https://github.com/app-generator/devtool-python-converter/tree/master/inputs

Like this, we have a unified INPUT.

**Comment by app-generator** [comment]
Hello @masoom80 

I'm overloaded and not able to patch this case. 

Please do some R&D overt this topic and let me know the issues. 

Ty!

**Comment by masoom80** [comment]
Hello @app-generator
Is this bug fixed?

**Comment by app-generator** [comment]
Not tested, but we can postpone the work for a few days. 

Happy new year! 

See u all in 2023. 
🚀🚀

P.S. I'm back on the 2nd.JAN

**Comment by app-generator** [comment]
Tested & Validated in TAG `v1.0.7`
Ty!
