### ISSUE TITLE
Export Option -  On page injection | Enhancement

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#19]
Hello!

> Note: the PDF, should be removed (being unavailable) in this drop. 

Would be nice to have the export data injected into the page with a download control on the top right. 
The layout  (similar to the Models conversion): 

- centered, fixed height (scrollable)
- download option on the top right corner (similar to the `copy` option for models)
- formated (SQL, JSON especially)

Like this, the user can visualize the data, and later decide to download it. 

Ty!

**Comment by alivarastepour** [comment]
Hi @app-generator 
I don't assume this was discussed in initial chats. it takes a great deal of time to implement.

**Comment by app-generator** [comment]
Yes, this is correct. 
We can leave it for the 2nd drop (starts soon).
Ty @alivarastepour

**Comment by alivarastepour** [comment]
> Hello!
> 
> > Note: the PDF, should be removed (being unavailable) in this drop.
> 
> Would be nice to have the export data injected into the page with a download control on the top right. The layout (similar to the Models conversion):
> 
> * centered, fixed height (scrollable)
> * download option on the top right corner (similar to the `copy` option for models)
> * formated (SQL, JSON especially)
> 
> Like this, the user can visualize the data, and later decide to download it.
> 
> Ty!

Hi @app-generator 
what is your suggestion for showing CSV output in the browser?

**Comment by app-generator** [comment]
Hello guys, 

the page injection of the data works, but the exports are accumulated. I mean:

- the user selects the JSON export -> Ok
- the user selects (same page) SQL export -> Ok
- User clicks to download the SQL -> **NOT OK**
  - the app sends two files for download. 

The desired behavior: User downloads only the current file, not all files. 

Please take a look. Ty!

**Comment by app-generator** [comment]
Tested in version `v1.0.7`.
Validated. 

Ty guys!
