### ISSUE TITLE
OpenAPI -> Model translation

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#2]
## General Information

- User accesses the main page and drops an [OpenAPI](https://appseed.us/generator/openapi/) schema
- Supported formats:
  - `JSON`, `Yaml` 
- [OpenAPI Visual Tool](https://appseed.us/generator/openapi/): https://appseed.us/generator/openapi/
  - Provides only JSON

The system replies with the Models definition extracted from the input files. 
The syntax of the returned code should be compliant with `Flask` and `Django`

### Translation rules (common to all converters)

- ID provided by default (integer, autoincremented)
- The types of fields should be detected using a simple guessing
  - nothing fancy, we can iterate later over this
- Once the model is provided, the user can:
  - specify the type for each column
  - regenerate the model definition

**Comment by Mortrest** [comment]
The output should be a file? or a text that shows in browser?

**Comment by app-generator** [comment]
Browser, using a simple formatting library that prettifies the output.
Also, a copy button should be nice for a better UX, .. but this can be added anytime later.

**Comment by masoom80** [comment]
> 

Translation from openapi(Yaml and json) is added.
regenerate is Under Construction.

**Comment by app-generator** [comment]
hello @Mortrest 

The file is sent to the server, I see a message in the CLI but nothing is returned to the user. 
In all cases (all other conversions as well) the result should be returned to the user.

In the latest version, nothing is returned to the user once `GENERATE` button is cliked. 

Please take a look. Ty! 

P.S. for tests, I'm using JSON files from this repo:
https://github.com/app-generator/devtool-openapi-parser/tree/main/io-samples

**Comment by masoom80** [comment]
> ases (all other conversions as well) the result should be returned to the user.
> 
> In the
hi there!
I tested it again and it's working(the codes are sent and shown properly)!
make sure your browser did not cache the previous data(refresh the page using shift+f5 and try again)

**Comment by app-generator** [comment]
There is a CORS Issue.

I'm using Chrome. 

![image](https://user-images.githubusercontent.com/51070104/205895601-09b81821-c719-410e-b909-f907e1794490.png)

**Comment by masoom80** [comment]
> There is a CORS Issue.
> 
> I'm using Chrome.
> 
> ![image](https://user-images.githubusercontent.com/51070104/205895601-09b81821-c719-410e-b909-f907e1794490.png)

did you force refresh the page (shift+f5)?

**Comment by app-generator** [comment]
yes, and also use incognito.

**Comment by alivarastepour** [comment]
> There is a CORS Issue.
> 
> I'm using Chrome.
> 
> ![image](https://user-images.githubusercontent.com/51070104/205895601-09b81821-c719-410e-b909-f907e1794490.png)

use 127.0.0.1 instead of localhost in URL.

**Comment by app-generator** [comment]
Solve it. Please Update

CORS default policy cut the errors

**Comment by app-generator** [comment]
I will re-test all. 
get back soon
🚀🚀

**Comment by app-generator** [comment]
Validated. Closing. 
ty guys!
