### ISSUE TITLE
JS Code - Remove hardcoded backend address

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#20]
Hello team,

`dnd.js` uses a hard-coded backend address and this makes the product broken when a different address is used: 

Please take a look, ty!

![image](https://user-images.githubusercontent.com/51070104/207794738-02492e74-aad1-4d5b-9736-e2c41e913143.png)

**Comment by app-generator** [comment]
Hello @alivarastepour 

Just update the path with `/` .. seems to work.
Please make supplementary tests.

ty!

**Comment by alivarastepour** [comment]
since we are not in a node environment, I can not use env variables. is there a special way on your mind?

**Comment by app-generator** [comment]
Validated. ty @alivarastepour 
Closing
