### ISSUE TITLE
valid URLs

### ISSUE THREAD

**Issue by alivarastepour** [app-generator/devtool-python-converter#27]
hi @app-generator 
would you please give some examples of valid csv URLs?

**Comment by app-generator** [comment]
Hello @alivarastepour 

For sure. Please process these two links: 

- https://github.com/app-generator/devtool-data-converter/blob/main/samples/data.csv
- https://docs.google.com/spreadsheets/d/1_z9OGyFnVKKvD2OidFNKF8vEXMzoddnLgbBCERLPgG8/edit#gid=0

The last one is a Google Sheet. Both formats should be supported. 

Ty!

**Comment by masoom80** [comment]
Hi @app-generator 
We will need a client_secrets.json file for the app to get the csv files from spreadsheets you can use the link below to get the json file:
[Using Google API for Python- where do I get the client_secrets.json file from](https://stackoverflow.com/questions/40136699/using-google-api-for-python-where-do-i-get-the-client-secrets-json-file-from)

**Comment by app-generator** [comment]
Let me check.

Please focus on the plain `cvs` source in the meantime: 
https://github.com/app-generator/devtool-data-converter/blob/main/samples/data.csv

Ty!

**Comment by app-generator** [comment]
Regarding URL, the UI should be updated to include an input field where the user inputs the URL.

Also, for the remote database, the UI requests the following input from the user: 

- DB Engine
- User/Pass
- Host /  PORT  

This information is used by `Pewee` reflection to import/manage data. 

The UI should be like this: 

- below the Drag & Drop box, we need a select with options: 
- Remote URL: 
  - CVS: if selected, a simple input becomes visible where the user can edit the URL
  - Database: if selected, the user can input:
    - DB Type: (all types supported by [Peewee](https://docs.peewee-orm.com/en/latest/) ): sqlite, mysql, postgresql
    - DB HOST (IP or name)
    - DB PORT
    - Credentials: USER/PASS
    
Once the user confirms  the above actions, here is the working flow for each source

### Remote CVS

- User can manipulate 500 rows only (limit in app config)

### Remote DB

- Check connection
  - on error, warn the user 
- [Peewee](https://docs.peewee-orm.com/en/latest/) makes the reflection and gets all models 
- The user selects the model to process
- Common conversions are applied to the table data:
  - datatables
  - charts
  - export `JSON`, `CSV` 

Note: the information provided by the user (DB data, credentials..) remains `on page` and the user should be able to change the table and apply conversions. 

@Mortrest @masoom80 @mchoopani please take a look.

Ty!

**Comment by app-generator** [comment]
Closing.
