### ISSUE TITLE
CSV -> DB Model

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#3]
Input: 

URL: https://docs.google.com/spreadsheets/d/1_z9OGyFnVKKvD2OidFNKF8vEXMzoddnLgbBCERLPgG8
File: [sales.csv](https://github.com/app-generator/devtool-python-converter/files/10082326/sales.csv)

### Translation rules (common to all converters)

- ID provided by default (integer, autoincremented)
- The types of fields should be detected using a simple guessing
  - nothing fancy, we can iterate later over this
- Once the model is provided, the user can:
  - specify the type for each column
  - regenerate the model definition

**Comment by masoom80** [comment]
> Input:
> 
> URL: https://docs.google.com/spreadsheets/d/1_z9OGyFnVKKvD2OidFNKF8vEXMzoddnLgbBCERLPgG8 File: [sales.csv](https://github.com/app-generator/devtool-python-converter/files/10082326/sales.csv)
> 
> ### Translation rules (common to all converters)
> * ID provided by default (integer, autoincremented)
> * The types of fields should be detected using a simple guessing
>   
>   * nothing fancy, we can iterate later over this
> * Once the model is provided, the user can:
>   
>   * specify the type for each column
>   * regenerate the model definition

csv to flask and django models is done!
regenerate is under construction.

**Comment by app-generator** [comment]
Really cool.
ty guys

**Comment by app-generator** [comment]
Hello @Mortrest 

Once the `generate` button is hit, the UI si not return the output to the user

The only thing is the log message `Model` printed by the CLI. 

Please take a look. ty!

**Comment by app-generator** [comment]
Working. Validated. 

Ty guys
