### ISSUE TITLE
DMBS URL - UI Constraints

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#31]
Hello @masoom80 & the team! 

The UI should be updated as below: 

- IP field can also accept domains and subdomains (with or without paths). Here are valid inputs:
  - 127.90.12.24
  - 127.90.12.24/path1/path2
  - appseed.us
  - db.appseed.us/path1
  - appseed.us/path2/path_asdasdasdsa
- DB Driver: should be a combo with the DB supported by PeeWee:
  - `sqlite`, `mysql`, `postgresql`
- Table Name should start disabled. 
  - Once the connection is made and the reflection is successful, this combo is populated with the tables pulled from the DB 

For any Q, I'm here. 

Ty guys!

**Comment by app-generator** [comment]
Hello @alivarastepour 

I need a sample here. Please attach a screen with the expected input for a distant SQLite DB:

https://github.com/app-generator/sample-flask-sqlite-source/blob/master/apps/db.sqlite3

Ty!

**Comment by alivarastepour** [comment]
> Hello @alivarastepour
> 
> I need a sample here. Please attach a screen with the expected input for a distant SQLite DB:
> 
> https://github.com/app-generator/sample-flask-sqlite-source/blob/master/apps/db.sqlite3
> 
> Ty!

hi @app-generator 
Would you please explain this more explicitly? I did not follow.

**Comment by alivarastepour** [comment]
> Hello @alivarastepour
> 
> I need a sample here. Please attach a screen with the expected input for a distant SQLite DB:
> 
> https://github.com/app-generator/sample-flask-sqlite-source/blob/master/apps/db.sqlite3
> 
> Ty!

please review [here](https://github.com/app-generator/devtool-python-converter/issues/35#issuecomment-1374482397).

**Comment by app-generator** [comment]
Validated. Closing.
Ty guys!
