### ISSUE TITLE
DB Import [Wrong Credentials] - Leads to error 500 (no message for user) 

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#35]
When the user provides a wrong connection URI or bad credentials, the server raises an error and no reply to the user.  

> Tested in version `v1.0.7`

- In all ERROR cases, the user should be informed. 

```log
  File "D:\work\repo-tools\devtool-python-converter\env\Lib\site-packages\pymysql\connections.py", line 664, in connect
    raise exc
peewee.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")  
```

**Comment by app-generator** [comment]
Hello guys!

this cannot be tested in the latest version because the connection is broken in all cases.

https://github.com/app-generator/devtool-python-converter/issues/34#issuecomment-1368774957

**Comment by alivarastepour** [comment]
> Hello guys!
> 
> this cannot be tested in the latest version because the connection is broken in all cases.
> 
> [#34 (comment)](https://github.com/app-generator/devtool-python-converter/issues/34#issuecomment-1368774957)

hi,
for testing purposes, we modified the flow a little bit; we will switch to the mentioned flow as soon as we figure how to start a DBMS remote server(help wanted anyway; plz review #36 ).
this is how you can test the flow for now:
assuming that `inputs` folder is present, provide `inputs/api.sqlite3` as a value for `dbname`, leave other fields empty and connect. then you can test the rest of the flow.
for further Q we are here. let us know.
ty!

**Comment by app-generator** [comment]
Hello @alivarastepour 

Please attach a screen with a working case. 

P.S. No worries, in all cases we will try to assist. The tool is tricky BUT, the hard part is already done. 
Thanks again for your work.

**Comment by alivarastepour** [comment]
![image](https://user-images.githubusercontent.com/81034797/211153103-fd1e1d20-893e-4d67-817d-684d106d4454.png)


![image](https://user-images.githubusercontent.com/81034797/211153153-e967fb19-39f5-4af5-ad26-e9f306e47e2a.png)


![image](https://user-images.githubusercontent.com/81034797/211153163-714f5be0-fbbc-4fdb-81b3-44d276d390a7.png)


![image](https://user-images.githubusercontent.com/81034797/211153199-9b72b15f-9bf0-433c-be3f-3bf8ae829bc4.png)

**Comment by app-generator** [comment]
looks good for SQLite

**Comment by app-generator** [comment]
Validated. Closing.
Ty!
