### ISSUE TITLE
Remote DBMS setup 

### ISSUE THREAD

**Issue by alivarastepour** [app-generator/devtool-python-converter#36]
Hi @app-generator 
Would you please give me an step by step guide on how to use the given sqlite file as remote dbms url?

**Comment by app-generator** [comment]
Hello @alivarastepour 

For sure. For `SQLITE` being only a path, the simple way is this: 

- Move the `DB DRIVER` to be the first field (on top of others)
  - On top of IP/DOMAIN
- And simply provide the URI of the file in the IP field: 

This might be the easiest & intuitive solution for the user. 

> here is an input that can be used for tests:

https://github.com/app-generator/sample-flask-sqlite-source/blob/master/apps/db.sqlite3

For further Q, I'm here. 

Ty! 

![image](https://user-images.githubusercontent.com/51070104/210216277-7e136ed8-e6b2-4954-a77b-9be3d448ec5d.png)

**Comment by alivarastepour** [comment]
what does moving DB driver to the top have to do with anything? I did not understand. and what about the other fields(port, DB name, user, pass)?

**Comment by alivarastepour** [comment]
> Hello @alivarastepour
> 
> For sure. For `SQLITE` being only a path, the simple way is this:
> 
> * Move the `DB DRIVER` to be the first field (on top of others)
>   
>   * On top of IP/DOMAIN
> * And simply provide the URI of the file in the IP field:
> 
> This might be the easiest & intuitive solution for the user.
> 
> > here is an input that can be used for tests:
> 
> https://github.com/app-generator/sample-flask-sqlite-source/blob/master/apps/db.sqlite3
> 
> For further Q, I'm here.
> 
> Ty!
> 
> ![image](https://user-images.githubusercontent.com/51070104/210216277-7e136ed8-e6b2-4954-a77b-9be3d448ec5d.png)


what does moving DB driver to the top have to do with anything? I did not understand. and what about the other fields(port, DB name, user, pass)?

**Comment by app-generator** [comment]
Hello @alivarastepour 

Please ignore moving the DB Driver field on top. 

For SQLite, being passwordless, DBname, user & password can be ignored. 

Feel free to provide a solution that makes sense to you and can be coded quickly.

The goal is to make the flow usable in both cases, using the most simple UI/UX possible. 

- Relational DBMS (MySql, PgSQL)
- SQLite 

For Q, I'm here or via Discord: 

Sm0ke#7120

Ty @alivarastepour

**Comment by alivarastepour** [comment]
> Hello @alivarastepour
> 
> Please ignore moving the DB Driver field on top.
> 
> For SQLite, being passwordless, DBname, user & password can be ignored.
> 
> Feel free to provide a solution that makes sense to you and can be coded quickly.
> 
> The goal is to make the flow usable in both cases, using the most simple UI/UX possible.
> 
> * Relational DBMS (MySql, PgSQL)
> * SQLite
> 
> For Q, I'm here or via Discord:
> 
> Sm0ke#7120
> 
> Ty @alivarastepour

I did what you said but I am still unable to fetch table names.
here is the form:

![image](https://user-images.githubusercontent.com/81034797/210225522-5d362a52-400a-4103-b1bd-32239dceee00.png)

**Comment by app-generator** [comment]
Hello team,

Just merged the latest PR. 
The remote DB import is not ok. fails all the time with `Could not connect` 

On the server side: 

```log
127.0.0.1 - - [16/Jan/2023 13:56:54] "POST / HTTP/1.1" 400 -
```

Please take a look.
TY!

**Comment by masoom80** [comment]
> Hello team,
> 
> Just merged the latest PR. The remote DB import is not ok. fails all the time with `Could not connect`
> 
> On the server side:
> 
> ```
> 127.0.0.1 - - [16/Jan/2023 13:56:54] "POST / HTTP/1.1" 400 -
> ```
> 
> Please take a look. TY!

Hi @app-generator 
Could you give me the credential used in your test?

**Comment by app-generator** [comment]
Hello @masoom80 

I'm using a minimal MySql database with just one table. 
This use-case can be easily tested using a local database because at the system level is not relevant if the IP is from a local network or a public one (same as for domain).

Some context & suggestions: 
- a few iterations ago, the feature was working (tables correctly detected)
- let's make it work for MySql, PgSQL .. etc and we can move the SQLite case to be dropped in the DROP ZONE

P.S. Guys .. let's make a push and close all the issues. Time is running fast.

Ty! :) 

![image](https://user-images.githubusercontent.com/51070104/212826006-92ef6b85-2e7d-4536-aa7a-0dce02e52524.png)

**Comment by masoom80** [comment]
Hi @app-generator 
I just tested it and it's working.
![Screenshot 2023-01-17 161940](https://user-images.githubusercontent.com/91330997/212903584-98dbbbd6-8c14-485c-9759-4bcd76517e07.png)

**Comment by app-generator** [comment]
Helo @masoom80,

The feature usability flow looks good. I was not pulling the latest sources for my previous tests (dummy).

A few things need to be fixed:

- The export is not working (all conversions)
- in the 2nd view, the `connect` button should disappear

Please take a look. Ty! 

![image](https://user-images.githubusercontent.com/51070104/213104123-03c1f8ad-fb7e-4a46-b8a2-0d867194c647.png)
