### ISSUE TITLE
CSV Files - Charts Not Visible

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#41]
Hello team,

here is the flow to reproduce: 

- Drop `csv_sales.csv` from inputs folder
- Select `Charts` option
- Chart Type: LINE
- X Axis: price
- Y Axis: Purchase Date

The chart is empty. 

Please take a look. Ty! 

![image](https://user-images.githubusercontent.com/51070104/213107927-22991c22-660e-45e9-8dc1-ffec97705e9c.png)

**Comment by alivarastepour** [comment]
hi @app-generator 
this is an issue with the chartjs library. the y axis must be of numeric type.

**Comment by app-generator** [comment]
noted. ty

**Comment by masoom80** [comment]
Hello @app-generator 
could you please check this bug?

**Comment by app-generator** [comment]
Hello @masoom80 

Yep, the product is scheduled for pre-release tests soon.
Ty!

**Comment by app-generator** [comment]
Hello @masoom80 

Tried this set up and the chart is OK. 
We can close it. TY! 

- drop `cvs_sales`
- select charts
- select LINE chart
- On-X -> Purchase DATA
- on-Y -> PRICE

![image](https://user-images.githubusercontent.com/51070104/216753150-5e3b73e1-73dd-43b7-a0aa-84dcce6b1262.png)
