### ISSUE TITLE
The Status - What Items are actually done

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#7]
Hello guys!

Thanks for all the work. 

Please mark on the README all finished items. 

> Note: this first iteration should have all items flagged with `Drop 1` (Delivery column)

Another point: the output for all conversions, should be returned in the UI to the calling user. I will start testing the features, one by one. 

![image](https://user-images.githubusercontent.com/51070104/205884831-cf6d6428-0b47-4a58-9416-ba625fad5438.png)

**Comment by alivarastepour** [comment]
explained [here](https://github.com/app-generator/devtool-python-converter/pull/9#issue-1478883112). take a look plz.

**Comment by app-generator** [comment]
noted. ty Ali. 
I'm on full testing.
