### ISSUE TITLE
CVS -> DataTable 

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#8]
Hello @Mortrest 

The input file is successfully uploaded. 

Once the `GENERATE` button is hit, nothing happens. 

Please double-check. ty! 

![image](https://user-images.githubusercontent.com/51070104/205890136-e72d9378-e454-4028-9d39-e5954b2bc36b.png)

**Comment by app-generator** [comment]
hello @Mortrest 

The feature works, but the DT view is generated in another window. 
As a general rule, all outputs (models, charts.. etc) should stay in the same window. 

Please display the generated data table below the controls, just like for charts. 

Might be a good idea to use the full available width (some CSV's can have many rows).

Ty

**Comment by alivarastepour** [comment]
> hello @Mortrest 
> 
> The feature works, but the DT view is generated in another window. 
> As a general rule, all outputs (models, charts.. etc) should stay in the same window. 
> 
> Please display the generated data table below the controls, just like for charts. 
> 
> Might be a good idea to use the full available width (some CSV's can have many rows).
> 
> Ty

@masoom80 please review this.

**Comment by app-generator** [comment]
Validated. Closing.
Ty Guys
